name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: publish
      run: dotnet publish -c Release
    - name: collect
      shell: pwsh
      run: |
        $root = pwd
        cd bin/Release/net6.0/win-x64/publish
        Copy-Item -Path GooDic.Fluent.Plugin.dll,AngleSharp.dll,netstandard.dll -Destination $root -Force -Verbose
    - name: upload archive
      uses: actions/upload-artifact@v3
      with:
        name: GooDic.Fluent.Plugin
        path: |
          GooDic.Fluent.Plugin.dll
          AngleSharp.dll
          netstandard.dll
          pluginsInfo.json
